### ISSUE TITLE
generic tar extract support (linux/mac setup fails with *.xz files)

### ISSUE THREAD

**Issue by sobkowiak** [devonfw/devon-ide#169]
I have downloaded the latest version of ide scripts from https://repo1.maven.org/maven2/com/devonfw/tools/ide/devon-ide-scripts/3.0.0-beta11/. The command `setup` has problem with installation of nodejs. The script cannot handle files with extension `*.xz`

````
*** Setting up node ***
Starting installation of node.js to /home/ksobkowiak/work/tmp/devon-ide-scripts-3.0.0-beta11/software/node from https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz
Artifact already exists at /home/ksobkowiak/Downloads/node.js-v10.16.0-linux.tar.xz
To force update please delete the file and run again.

******** ATTENTION ********
ERROR: Unknown archive format: .xz. Can not extract /home/ksobkowiak/Downloads/node.js-v10.16.0-linux.tar.xz
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
ERROR: command 'node setup' failed with exit code 255
````

Category: Bug

Severity: High

Steps to reproduce (In case of bug):

- Unpack the latest version of `devon-ide-scripts-3.0.0-beta11.tar.gz` and run the `setup` script

Environment - Fedora 30, devon-ide 3.0.0-beta11

**Comment by markusschuh** [comment]
I'd suggest to add compatibility to use xz format for the archives - but at the same time I recommend to use gz as far as possible - and add this recommendation to the documentation. For example, even nodejs for linux x64 is still available in tar.gz archive format. I just needs a switch to  "All download options" to locate the related URL.

The issue is just, that "tar" isn't identical on all platforms - and it is a bit difficult to detect / ensure compatibility of tar with xz. To my knowledge
- macOS uses "bsdtar" and has xz compatibility built in since about 10.9.0 or so
- most other devon-ide supported enviroments use GNU tar, which delegates any compression/decompression task to external utilities, which is "xz" in this case. "xz-utils" (or similar packages) are today typically part of default installations - but this is no must. Earlier or later somebody runs devon-ide on a system without xz installed.

Therefore use of tar.gz is still the most compatible one - and many software is still distributed this way in addition to tar.xz as another option. XZ is just the default, since this "extended compress" is a bit more efficient than gz in terms of both comressed size as well as compress/decompress times.

**Comment by hohwille** [comment]
From @markusschuh in #170 
> A simple
`tar xf $archive`
will work for all archives, first "tar"ed, then - optionally - compressed with either gzip, bzip2 or xz.
The current code within "functions" tries to redo the internal tar logic within the outside scripting. This looks ineffective. Also it unnecessarily introduces small glitches - e.g the *.tar.bz2 case is not yet handled properly.

Agreed. I will change that as suggested.
