### ISSUE TITLE
bash coding style harmonizing

### ISSUE THREAD

**Issue by markusschuh** [devonfw/devon-ide#66]
Category: Enhancement
Severity: Low
Description of enhancement:

I propose some coding style changes for the bash code - strongly influenced by [The Bash Hackers Wiki](https://wiki.bash-hackers.org/) -  which IMHO do better match "modern bash code" - without introducing additional bash features, which may run into compatibility issues on systems, where the oldest bash version is (per default) installed. (Currently probably the macOS /bin/bash 3.2.x)
In case of some agreement here, I'm open to realise them and add a pull request. Of course such a change could be postponed to next release.

The proposed changes:
1. There may still be systems (some linux distros) which have bash installed at /usr/bin/bash instead of /bin/bash.  For that reason the most compatible shebang known today is:
#!/usr/bin/env  bash

2. It is a very consistent use to only use brace surrounded var names within shell scripts. But except a few cases, it is unnecessary. Code may be easier to read, if braces are only used where necessary. Since is especially true for cases where a) single char var names are used  b) additional double quotes are necessary to avoid unwanted split. Example:   "$@" instead of "${@}". (The majority of existing scripts uses the shorter coding)

3. The use of bash's double brackets for conditions has many advantages. E.g. it implicitly double quotes anyway, allows globing and more. Since a few double brackets are already in use within devon-ide-scripts anyway - why not use them everywhere?

4.  Some of the currently existing code could be made more "bash-alike", though it may be readable a bit harder for non-script coders then. E.g. the current "software_version=$(doGetVariable ECLIPSE_VERSION 2018-12)" is nothing else than "software_version=${ECLIPSE_VERSION=-2018-12}"

Any comments?

**Comment by hohwille** [comment]
@markusschuh Thanks for your feedback and suggested improvements 👍 

My comments on this:
1. fine for me. IMHO platforms where no /bin/bash is present are not really relevant to use but why not making it more portable and follow best practices. (Please also be aware that some of the scripts are actually sourced and the shebang is only present for editor syntax highlighting.)

2. I personally disagree with this one. I decided to use curly braces everywhere in the scripts to make it consistent and easier to read. If you add the braces here and omit them somewhere else you would IMHO introduce more confusion. Please also note that we now have `devon.properties` files that may look like bash scripts but here omitting curly braces will not work.

3. In this case I decided to only use double brackets in the very few cases where they are required and I could not find an alternate solution. I am personally a fan of ZSH (and oh-my-zsh) and sometimes test some of the snippets in my local zsh shell. However, double brackets seem to be a bash proprietary syntax that does not work in other shells. So I see your arguments and see both pros and cons for doing 3. as well as omitting 3. If you want to become more of a contributor of devon-ide and would benefit from this change, I would not mind it. If I stay the maintainer of all this, I do not see the advantages of this change.

4. Valid point. I just did not think of this. Your suggestion is a nice simplification. We should also remove the function `doGetVariable` then and replace this consistenly as you suggest.

> In case of some agreement here, I'm open to realise them and add a pull request. 

I would be very happy to receive a PR. :)

**Comment by markschuh** [comment]
Some more comments:

1.  /bin/bash is not a standard, but as it is meanwhile a recommendation of the [LFH](https://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/Linux-Filesystem-Hierarchy.html#bin) major linux distribution should all have it as /bin/bash since some years. I have mostly macOS in my mind with this change: There the /bin/bash is still a v3 one - and if ever some bashv4 syntax slips into the bash scripts (in any product) then macOS users are the ones who will have an issue. But a macOS developer should anyway use [brew](https://brew.sh) - or one of the alternatives - and install an up-to-date bash into /usr/local/bin/bash.  Using the "#!/usr/bin/env bash" will take any bash first in path - a bit vagueness, but more flexible. see https://serverfault.com/a/865880

2. I agree that braces must exist in some case - like the devon.properties or when variables are placed next to other strings. I also understand the argument about consistency. But especially for the short / special variables this usage is quite unusual and does not make read easier. Anyway - I won't touch this. Nevertheless, there currently exists a few number of usages without braces within devon-ide, which you should fix due to consistency ;)

3. I added this proposal also due to more consistency - a double bracket had already been introduced into the devon-ide scripts. So why not use them everywhere? This helps others, to introduce new errors, since the double brackets are far more "forgiving" I had used zsh in the past a lot, and I thought, for double brackets the syntax is the same as in bash. But I may have missed newer changes.
But especially with respect to single brackets, zsh had introduced a POSIX incompatible change which IMHO is a bit bad for script compatibility: in zsh you can use: `file="a f"; if [ -f $file ]; echo exists; fi`  This may help for interactive use - but won't run in other shells. In case you don't even had a bash, unix would fall back using the /usr/bin/[ - and this would fail due to an additional option "f". In bash it was decided to restrict this non-POSIX syntax to double brackets. For this simple case it is of course easy enough to just use `file="a f"; if [ -f "$file" ]; echo exists; fi` for maximum compatibility. I will check the bracket usage again - and if there are some hot candidates for lot easier code, I'll add another PR.

4. I will do this changes inside a new PR. I don't want to include them into #64 - where the changes match to Shellcheck findings.

**Comment by hohwille** [comment]
For the record: The PR for this issue is #64 
@markusschuh Please add issue id to commit messages for auto-linking. See https://github.com/devonfw-wiki/devon4j/wiki/devonfw-code-contribution#code-contribution

**Comment by hohwille** [comment]
So I have resolved 1. and 4. now. Also systematically changed from backquote syntax (`command`) to dollar syntax (`$(command)`). I still have no clue why this is really better, but hope this makes shellcheck and bash coders more happy.

**Comment by hohwille** [comment]
So to conclude:
From my personal perspective the important improvements are done.
We seem to be aligned for 2.
For 3. I am happy to accept a PR. However, as you have seen there is a lot of movement going on. So maybe you want to wait till the end of beta phase in a few weeks...

**Comment by hohwille** [comment]
As the rest is nice to have. I already close this issue to proceed foreward. I am still happy to receive PRs on this.
